### PR TITLE
DBAL Transaction Middleware

### PR DESCRIPTION
**Pull request by cubanec**

### CODE REVIEW

**Comment by rosstuck** [comment]
Looks good! We don't have any integration tests right now unfortunately, have you tried this on an actual project? :)

**Comment by cubanec** [comment]
@rosstuck currently I am implementing ZF based application with Tactician command bus. Since I use doctrine DBAL without ORM I was missing such a middleware. I've tested it installing `thephpleague/tactician-doctrine` from my fork, my app depends on this code and it works expected.

**Comment by snapshotpl** [comment]
@cubanec can you add php 7.1 enviroment to `.travis`?

**Comment by snapshotpl** [comment]
Project require `"doctrine/orm": "~2.4"`, now sometimes we need only dbal, idea to resolve this?

**Comment by rosstuck** [comment]
@cubanec Sounds legit.

@snapshotpl Good call on 7.1, I need to add it to all the tactician repos. 😩 

If I remember correctly, ORM relies on DBAL connection. What if we change the dep to DBAL with ORM in the suggested category?

**Comment by snapshotpl** [comment]
@rosstuck make sense. However it will introduce compatibility break for current users.

**Comment by rosstuck** [comment]
Hmm, if they're pulling in ORM now, they already have a DBAL version so it should match requirements and still pass. If they start off using DBAL from this version and downgrade, it'll be an issue but I can't see that as a big scenario.

Any advice on Dohmsraken, er, @rdohms?

**Comment by cubanec** [comment]
@rosstuck here, you can check proposal of changed dependencies 4d7ea39, but as mentioned by @snapshotpl it will introduce a compatibility break for current users using ORM Transaction Middleware (orm dependency will disappear)

Possible solution would be to bump major version number to 2.*.* when merging this into master

When bumping major version it would be also possible to require PHP v 7+ and drop support for old PHP versions

**Comment by rdohms** [comment]
I don't think the dependency change is a breaking one.
People will run a `composer install` and a bunch of stuff will get removed, if they rely on `doctrine/orm` then that will be in their own json already, so essentially they do not have to change anything on their end (unless they are wrongfully depending on a sub-package to bring in a primary requirement, which is already questionable.)

So I would say this is no more then than a feature release.

**Comment by rosstuck** [comment]
Regarding the latest travis failure, it probably just needs this change: https://github.com/thephpleague/tactician-bundle/commit/1d9788a3b5346c21c47decdb183f642445da8631

Thanks for the changes and bumping DBAL back down to 2.4. :)

I'll give this another read through but I can tag a 1.1 from this today. 👍

**Comment by snapshotpl** [comment]
@cubanec @rosstuck looks perfect now. Ready to release? :)

**Comment by rosstuck** [comment]
New 1.1 release tagged. Thanks a ton for this contribution everyone, it's much appreciated! :)

**Pull request merged**
