### PR TITLE
Drop PHP under 7.1, support for dbal v3, update dependencies for tactician v1

### PR DESCRIPTION
**Pull request by snapshotpl**

### CODE REVIEW

**Comment by rubenrubiob** [comment]
I am interested in this too. Any chance to merge it @rosstuck ?

Thank you!

**Comment by cvele** [comment]
Very interested in the above too

**Comment by snapshotpl** [comment]
@rubenrubiob @cvele If you want to use this features I have release this in my fork https://github.com/snapshotpl/tactician-doctrine

**Comment by rubenrubiob** [comment]
It is an option that I contemplated. I know that this is a package that requires almost no maintenance, but do you intend to maintain it within your fork?

Same question for the base package, that I saw you already forked and adapted.

**Comment by rosstuck** [comment]
Tagged as version 1.2.0 :)

**Comment by rubenrubiob** [comment]
Thank you very much @rosstuck !

**Comment by rosstuck** [comment]
Thanks but kudos to @snapshotpl, he did all the work :heart:

**Comment by rubenrubiob** [comment]
Of course, many thanks to @snapshotpl too!

**Pull request merged**
