### PR TITLE
Allow DBAL v3

### PR DESCRIPTION
**Pull request by simPod**

### CODE REVIEW

**Comment by rosstuck** [comment]
So, here's the crappy part. There's two issues here:

- This PR allowed DBAL v3 into master, which is all the unreleased Tactician 2 stuff. Tagging a release off master will just break more stuff. To get a release for Tactician 1, I've made a branch on this repo called tactician-v1. Can you try to send a similar PR there?
- Furthermore, this PR (even for the newer Tactician 2 stuff) broke the build because DBAL v3 apparently doesn't have a ping() method anymore and this repo has a PingConnectionMiddleware. Therefore, we need to make that test conditional or at least more clever. I've switched it from Travis to Github Actions to help with that at least.

**Comment by simPod** [comment]
@rosstuck can we bump min php version on v1? I went to upgrade phpunit there but it's php v5.5+ and I kind of don't want to work with that. 🤔

**Comment by snapshotpl** [comment]
@simPod try to use https://github.com/Yoast/PHPUnit-Polyfills

**Comment by snapshotpl** [comment]
For first I think we should drop unsupported PHP versions.

**Comment by snapshotpl** [comment]
@simPod @rosstuck done in #29

**Pull request merged**
